using System;
using System.Collections.Generic;
using System.Web.DynamicData;
using System.Web.Security;
using System.Web.UI.WebControls;
using System.Linq;
using AbsenceManager.Security;

namespace AbsenceManager
{
    public partial class GridViewScreens_Edit : FieldTemplateUserControl
    {
        protected System.Web.DynamicData.MetaTable table, tableInsert;
        private string _UserName;

        private bool _hasOnScreenPermission;
        private bool _hasInlinePermission;

        protected bool HasInlinePermission
        {
            get { return _hasInlinePermission; }
        }

        protected bool HasOnScreenPermission
        {
            get { return _hasOnScreenPermission; }
        }

        protected bool PageReadOnly
        {
            get
            {
                AMRoleProvider gprp = (AMRoleProvider)System.Web.Security.Roles.Provider;

                ScreenPermissions sp = gprp.GetPermissionsForScreenInUser(table.Name, _UserName);

                return sp == ScreenPermissions.Read || sp == ScreenPermissions.None;
            }
        }

        protected bool ShowDeleteBtn
        {
            get
            {
                return true;
                //string path = this.Context.Request.AppRelativeCurrentExecutionFilePath;
                //return path.Contains("Roles")
                //    || path.Contains("Users")
                //    || path.Contains("Handlers")
                //    || path.Contains("Flights/Edit")
                //    || path.Contains("Areas/Edit");
            }
        }

        protected void Page_Init(object sender, EventArgs e)
        {
            var metaChildColumn = Column as MetaChildrenColumn;
            var metaForeignKeyColumn = metaChildColumn.ColumnInOtherTable as MetaForeignKeyColumn;

            if (metaChildColumn != null && metaForeignKeyColumn != null)
            {
                #region GridView/Update
                // Definir contexto/entidade
                GridDataSource.ContextTypeName = metaChildColumn.ChildTable.DataContextType.FullName;
                GridDataSource.EntitySetName = metaChildColumn.ChildTable.Name;

                // Definir update/delete/insert
                GridDataSource.EnableDelete = true;
                GridDataSource.EnableInsert = true;
                GridDataSource.EnableUpdate = true;
                //GridView1.AutoGenerateDeleteButton = true;
                //GridView1.AutoGenerateEditButton = true;

                // Get de uma instancia da MetaTable
                table = GridDataSource.GetTable();

                // Definir as datakeys da Gridview
                String[] keys = new String[metaChildColumn.ChildTable.PrimaryKeyColumns.Count];
                int i = 0;
                foreach (var keyColumn in metaChildColumn.ChildTable.PrimaryKeyColumns)
                {
                    keys[i] = keyColumn.Name;
                    i++;
                }
                GridView1.DataKeyNames = keys;

                // Gerar as colunas da gridview com o FieldTemplateRowGenerator
                // Filtrar a relação

                GridView1.ColumnsGenerator = new FieldTemplateRowGenerator(table, new string[] { metaForeignKeyColumn.Name });
                //GridView1.ColumnsGenerator = new FieldTemplateRowGenerator(table);

                // Filtros, FKs, Where clause
                GridDataSource.EntityTypeFilter = table.EntityType.Name;
                GridDataSource.Include = table.ForeignKeyColumnsNames;
                GridDataSource.AutoGenerateWhereClause = true;
                #endregion

                #region FormView/Insert
                //Insert
                // Definir contexto/entidade
                FormViewDataSource.ContextTypeName = metaChildColumn.ChildTable.DataContextType.FullName;
                FormViewDataSource.EntitySetName = metaChildColumn.ChildTable.Name;
                FormViewDataSource.EnableInsert = true;

                // Get de uma instancia da MetaTable
                tableInsert = FormViewDataSource.GetTable();

                // Filtros, FKs
                FormViewDataSource.EntityTypeFilter = tableInsert.EntityType.Name;
                FormViewDataSource.Include = tableInsert.ForeignKeyColumnsNames;

                // Pre-preenchimento das FKs do insert
                int j = 0;
                var dict = new Dictionary<string, object>();
                //if (Request.QueryString.Count > 0)
                foreach (String fkName in metaForeignKeyColumn.ForeignKeyNames)
                {
                    var fkColumn = metaChildColumn.ChildTable.GetColumn(fkName);
                    if (Request.QueryString.Count > 0)
                        dict.Add(fkColumn.Name, Request.QueryString[j]);
                    else
                        dict.Add(fkColumn.Name, 0);
                    j++;
                }

                FormView1.SetMetaTable(Global.DefaultModel.GetTable(tableInsert.Name), dict);
                #endregion
            }
            else
            {
                // throw an error if set on column other than MetaChildrenColumns
                throw new InvalidOperationException("The GridView FieldTemplate can only be used with MetaChildrenColumns");
            }
        }

        protected void Page_Load(object sender, EventArgs e)
        {
            AMRoleProvider gprp = (AMRoleProvider)System.Web.Security.Roles.Provider;
            _UserName = Membership.GetUser().UserName;

            // Page Read Only
            ScreenPermissions sp = gprp.GetPermissionsForScreenInUser(table.Name, _UserName);

            if (sp == ScreenPermissions.Write)
                _hasOnScreenPermission = _hasInlinePermission = true;
            else
            {
                _hasInlinePermission = sp == ScreenPermissions.Write;
                _hasOnScreenPermission = sp == ScreenPermissions.Write;
            }

            if (!PermissionsManager.IsInsertAvailable(table) || !_hasOnScreenPermission)
                InsertHyperLink.Visible = false;
        }

        protected override void OnDataBinding(EventArgs e)
        {
            base.OnDataBinding(e);

            //GridView
            var metaChildrenColumn = Column as MetaChildrenColumn;
            var metaForeignKeyColumn = metaChildrenColumn.ColumnInOtherTable as MetaForeignKeyColumn;
            int i = 0;

            foreach (String fkName in metaForeignKeyColumn.ForeignKeyNames)
            {
                var fkColumn = metaChildrenColumn.ChildTable.GetColumn(fkName);

                var param = new Parameter();
                param.Name = fkColumn.Name;
                param.Type = fkColumn.TypeCode;

                if (Request.QueryString.Count > 0)
                {
                    if (Request.QueryString[i] == "False")
                        param.DefaultValue = "0";
                    else if (Request.QueryString[i] == "True")
                        param.DefaultValue = "1";
                    else
                        param.DefaultValue = Request.QueryString[i];
                }
                else
                    param.DefaultValue = "0";

                GridDataSource.WhereParameters.Add(param);

                i++;
            }
        }

        // Não mostar a FormView no momento em que se edita um registo da GridView
        protected void GridView1_RowEditing(object sender, EventArgs e)
        {
            FormView1.ChangeMode(FormViewMode.ReadOnly);
        }

        protected void GridView1_SelectedIndexChanging(object sender, EventArgs e)
        {
            GridView1.EditIndex = -1;
            FormView1.ChangeMode(FormViewMode.ReadOnly);
        }

        protected void GridView1_RowDeleted(object sender, GridViewDeletedEventArgs e)
        {
            if (e.Exception != null)
            {
                GeneralHelpers.ShowJavascriptAlert("O registo não pode ser apagado neste momento.");
                e.ExceptionHandled = true;
            }
        }

        // Refresh da GridView após um insert
        protected void FormViewDataSource_Inserted(object sender, EntityDataSourceChangedEventArgs e)
        {
            if (e.Exception != null)
            {
                customValida.IsValid = false;
                customValida.ErrorMessage = e.Exception.Message;
                e.ExceptionHandled = true;
            }
            else GridView1.DataBind();
        }

        protected void FormViewDataSource_Inserting(object sender, EntityDataSourceChangingEventArgs e)
        {
            Type entityType = e.Entity.GetType();
            long? Id = long.Parse(Context.Request.QueryString["ID"]);

            RoleApplicationScreen ras = e.Entity as RoleApplicationScreen;
            ras.RoleID = (long)Id;

            using (AM_Entities ent = new AM_Entities())
            {
                int ct = (from r in ent.RoleApplicationScreens
                          where r.ApplicationScreenID == ras.ApplicationScreenID
                          && r.RoleID == ras.RoleID
                          select r.ID).ToList().Count();

                if (ct > 0)
                {
                    customValida.ErrorMessage = "Cannot insert duplicate Application Screen for this Role.";
                    e.Cancel = true;
                    customValida.IsValid = false;
                }
            }
        }

        // Toogle do panel de insert
        protected void lkbToggle_Click(object sender, EventArgs e)
        {
            FormViewMode fvm = (FormView1.CurrentMode == FormViewMode.ReadOnly) ? FormViewMode.Insert : FormViewMode.ReadOnly;
            FormView1.ChangeMode(fvm);
        }
    }
}
